[package]
name = "bevy_examples"
version = "0.8.0-dev"
edition = "2021"
description = "Helper crate to display examples"
publish = false
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
