[package]
name = "build-template-docs"
version = "0.9.0"
edition = "2021"
description = "handle templated docs from Cargo file in Bevy"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
toml = "0.5"
tera = "1.15"
serde = { version = "1.0", features = [ "derive" ] }
bitflags = "1.3"
