name: Daily Jobs

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly

jobs:
  build-and-install-on-iOS:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios

      - name: Build app for iOS
        run: |
          cd examples/mobile
          make xcodebuild-iphone
          mkdir Payload
          mv build/Build/Products/Debug-iphoneos/bevy_mobile_example.app Payload
          zip -r bevy_mobile_example.zip Payload
          mv bevy_mobile_example.zip bevy_mobile_example.ipa

      - name: Upload to Browser Stack
        run: |
          curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_PASSWORD }}" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@examples/mobile/bevy_mobile_example.ipa" \
            -F "custom_id=ios-$GITHUB_RUN_ID"

      - name: Run Example
        run: |
          cd .github/start-mobile-example
          npm install
          npm install -g @percy/cli@latest
          npx percy app:exec -- npm run mobile
        env:
          BROWSERSTACK_APP_ID: ios-${{ github.run_id }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_PASSWORD }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          DEVICE: "iPhone 13"
          OS_VERSION: "15"
          PERCY_PARTIAL_BUILD: 1

      - name: Save screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-ios
          path: .github/start-mobile-example/*.png

      - name: Wait for screenshots comparison
        run: |
          npx percy build:wait --project 80a5aff7/Bevy --commit ${{ github.sha }} --fail-on-changes --pass-if-approved
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi

      - name: Install Cargo APK
        run: cargo install --force cargo-apk

      - name: Build app for Android
        run: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --package bevy_mobile_example
        env: 
          # This will reduce the APK size from 1GB to ~200MB
          CARGO_PROFILE_DEV_DEBUG: false

      - name: Upload to Browser Stack
        run: |
          curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_PASSWORD }}" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@target/debug/apk/bevyexample.apk" \
            -F "custom_id=android-$GITHUB_RUN_ID"

      - name: Run Example
        run: |
          cd .github/start-mobile-example
          npm install
          npm install -g @percy/cli@latest
          npx percy app:exec -- npm run mobile
        env:
          BROWSERSTACK_APP_ID: android-${{ github.run_id }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_PASSWORD }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          DEVICE: "Samsung Galaxy S23"
          OS_VERSION: "13.0"
          PERCY_PARTIAL_BUILD: 1

      - name: Save screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: screenshots-android
          path: .github/start-mobile-example/*.png

      - name: Wait for screenshots comparison
        run: |
          npx percy build:wait --project 80a5aff7/Bevy --commit ${{ github.sha }} --fail-on-changes --pass-if-approved
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
