name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Setup unique branch name
        run: echo BRANCH_NAME=release-$(date +%s) >> $GITHUB_ENV
      - name: Setup release
        run: |
          # git checkout -b ${{ env.BRANCH_NAME }}
          cargo release minor --workspace --no-publish --execute --no-tag
          # git push
      - name: Create PR
        uses: peter-evans/create-pull-request@v3

