name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo-release
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-release
      - name: Setup unique branch name
        run: echo BRANCH_NAME=release-$(date +%s) >> $GITHUB_ENV
      - name: Setup release
        run: |
          git config user.name 'Bevy Auto Releaser'
          git config user.email 'bevy@users.noreply.github.com'
          git checkout -b ${{ env.BRANCH_NAME }}
          cargo release minor --workspace --no-publish --execute --no-tag --no-confirm
          # git push
      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: "main"
          pr_title: "Preparing Release"

